import { Container, Divider, VStack } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";

interface Props {
  children: React.ReactNode;
  title?: string;
}

const Layout = ({ children, title = "Next App" }: Props) => {
  return (
    <Container maxW="container.xl">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: "100vh", margin: "0 auto -50px" }}>
        {children}
      </main>

      <footer>
        <VStack>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </VStack>
      </footer>
    </Container>
  );
};

export default Layout;
