import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Link &rarr;</h2>
            <p>
              <li>
                <Link href="/link" passHref>
                  <a>Link</a>
                </Link>
              </li>
              <li>
                <Link href="/link/PageOne" passHref>
                  <a>PageOne</a>
                </Link>
              </li>
              <li>
                <Link href="/link/PageTwo" passHref>
                  <a>PageTwo</a>
                </Link>
              </li>
            </p>
          </div>

          <div className={styles.card}>
            <h2>Routing &rarr;</h2>
            <p>
              <li>
                <Link href="/routing/single/param" passHref>
                  <a>Single</a>
                </Link>
              </li>
              <li>
                <Link href="/routing/multiple/param1/param2" passHref>
                  <a>Multiple</a>
                </Link>
              </li>
              <li>
                <Link href="/routing/param0/param1/param2" passHref>
                  <a>Catch All</a>
                </Link>
              </li>
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
